[project]
name = "krux-file-signer"
version = "0.0.2"
description = "A python script to sign files and verify signatures in a airgapped manner"
authors = [
  {name = "odudex", email = "eduardo.schoenknecht@gmail.com"},
  {name = "qlrddev", email = "qlrddev@gmail.com"},
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
  "opencv-python>=4.8.0.76,<5.0.0",
  "qrcode>=8.0,<9.0",
]

[dependency-groups]
dev = [
  "black>=26.0,<27.0",
  "pylint>=4.0,<5.0",
  "poethepoet>=0.42,<1.0",
]

[tool.uv]
package = false

[tool.poe.tasks]
# format
format-src = "black src"
format.ref = "format-src"
black.ref = "format"

# lint
lint-src = "pylint src"
lint.ref = "lint-src"
pylint.ref = "lint"

# pre-commit
pre-commit = ["format", "lint"]

# ksigner shortcuts
# e.g. `uv run poe sign -f ../krux/README.md -o ../krux/pubkey.pem`
sign = "python src/ksigner.py sign"
verify = "python src/ksigner.py verify"
version = "python src/ksigner.py --version"
